2021/06/01 16:08:58 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api/channels/100000 HTTP/1.1", upstream: "http://172.30.0.4:80/api/channels/100000", host: "kubernetes.docker.internal"
2021/06/01 16:08:59 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api/channels/100000 HTTP/1.1", upstream: "http://172.30.0.4:80/api/channels/100000", host: "kubernetes.docker.internal"
2021/06/01 16:08:59 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api/channels/100000 HTTP/1.1", upstream: "http://172.30.0.4:80/api/channels/100000", host: "kubernetes.docker.internal"
2021/06/01 16:08:59 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api/channels/100000 HTTP/1.1", upstream: "http://172.30.0.4:80/api/channels/100000", host: "kubernetes.docker.internal"
2021/06/01 16:09:00 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api/channels/100000 HTTP/1.1", upstream: "http://172.30.0.4:80/api/channels/100000", host: "kubernetes.docker.internal"
2021/06/01 16:09:10 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /docs HTTP/1.1", upstream: "http://172.30.0.4:80/docs", host: "kubernetes.docker.internal"
2021/06/01 16:11:17 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api HTTP/1.1", upstream: "http://172.30.0.4:80/api", host: "kubernetes.docker.internal"
2021/06/01 16:11:25 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api HTTP/1.1", upstream: "http://172.30.0.4:80/api", host: "kubernetes.docker.internal"
2021/06/01 16:11:31 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api HTTP/1.1", upstream: "http://172.30.0.4:80/api", host: "kubernetes.docker.internal"
2021/06/01 16:14:06 [error] 31#31: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api HTTP/1.1", upstream: "http://172.30.0.4:8080/api", host: "kubernetes.docker.internal"
2021/06/01 16:14:06 [error] 31#31: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: alertifa_00, request: "GET /api HTTP/1.1", upstream: "http://172.30.0.4:8080/api", host: "kubernetes.docker.internal"
2021/06/01 16:48:43 [emerg] 1#1: host not found in upstream "fastapi" in /etc/nginx/conf.d/default.conf:34
